### ISSUE TITLE
Create header

### ISSUE THREAD

**Issue by aose-yuu** [aose-yuu/ademerjs#1]
## Todo

- [ ] Library name to go to Home
- [ ] Button to go to Documentation
- [ ] Button to go to GitHub
